/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 349361337
 */
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import javax.swing.Timer;
import thegameoflife.*;

public class DrawingArea extends javax.swing.JPanel {

    /**
     * Creates new form DrawingArea
     */
    int row;
    int col;

    public DrawingArea() {
        initComponents();
        TheGameOfLife.row = row;
        TheGameOfLife.col = col;
        TheGameOfLife.board[1][1] = true;
        TheGameOfLife.board[1][2] = true;
        TheGameOfLife.board[1][3] = true;
    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        for (int i = 0; i < row; i++) {
            for (int j = 0; j < col; j++) {
                g.drawRect(i * (getWidth() / row), j * (getHeight() / col), getWidth() / row, getHeight() / col);
                if (TheGameOfLife.board[i][j]) {
                    g.fillRect(i * (getWidth() / row), j * (getHeight() / col), getWidth() / row, getHeight() / col);
                }
            }
        }
    }

    public void mouseClicked(MouseEvent e) {

    }

    private class TimerListener implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            TheGameOfLife.checkNeighbors();
            repaint();
        }
    }
    
    public void anim() {
        Timer t = new Timer(50, new TimerListener());
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
